### ISSUE TITLE
石墨文档没权限访问

### ISSUE THREAD

**Issue by kimtony** [biquanlibai/blockchain-course#1]
大佬，石墨文档没权限访问
![image](https://user-images.githubusercontent.com/34413109/139820301-d89c34ba-45ed-42cd-90c5-6d10a0faa816.png)

**Comment by biquanlibai** [comment]
由于你的文件存在敏感信息，现已禁止分享。

我换个工具。。。

**Comment by biquanlibai** [comment]
已经更新为notion

**Comment by kimtony** [comment]
> 已经更新为notion

谢谢大佬的开源分享
